services:
    endroid.prediction_io.client:
        class: Endroid\PredictionIO\Client
        arguments: [ @endroid.prediction_io.event_client, @endroid.prediction_io.engine ]
        lazy: true
    endroid.prediction_io.event_client:
        class: predictionio\EventClient
        arguments: [ %endroid.prediction_io.app_key%, %endroid.prediction_io.event_server_url% ]
        lazy: true
    endroid.prediction_io.engine:
        class: predictionio\EngineClient
        arguments: [ %endroid.prediction_io.engine_url% ]
        lazy: true
